#!name=Test
#!desc=专门做测试用

[Rewrite]
^https:\/\/beta-luna\.douyin\.com\/luna\/commerce\/upsells_config\? - reject-dict
^https:\/\/api\.qishui\.com\/luna\/ads\/ - reject-dict
^https:\/\/beta-luna\.douyin\.com\/luna\/ads\/ - reject-dict
^https:\/\/webcast-open\.douyin\.com\/webcast\/openapi\/feed\/\? - reject-dict
^https:\/\/beta-luna\.douyin\.com\/luna\/treasure\/entrance\/config\? - reject-dict
^https:\/\/beta-luna\.douyin\.com\/luna\/activities\? - reject-dict
^https:\/\/beta-luna\.douyin\.com\/luna\/media_ads\? - reject-dict
^https:\/\/beta-luna\.douyin\.com\/luna\/commerce\/upsells\? - reject-dict
^https:\/\/beta-luna\.douyin\.com\/luna\/commerce\/v2\/commerce_info\? - reject-dict


[Script]
# 彩云天气真正有效的是这个，可以去掉下方助手
caiyun_json=type=http-response,pattern=^https?:\/\/wrapper\.cyapi\.cn\/v\d\/activity,requires-body=1,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/caiyun_json.js

# 汽水音乐
douyin_me = type=http-response, pattern=^https?:\/\/beta-luna\.douyin\.com\/luna\/me\?, script-path=https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js, requires-body=true
douyin_feed = type=http-response, pattern=^https?:\/\/beta-luna\.douyin\.com\/luna\/feed\/song-tab\?, script-path=https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js, requires-body=true
douyin_card = type=http-response, pattern=^https?:\/\/beta-luna\.douyin\.com\/luna\/card\?, script-path=https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js, requires-body=true
douyin_more = type=http-response, pattern=^https?:\/\/beta-luna\.douyin\.com\/luna\/more-panel\?, script-path=https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js, requires-body=true
douyin_recent = type=http-response, pattern=^https?:\/\/beta-luna\.douyin\.com\/luna\/me\/recently-played-media\?, script-path=https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js, requires-body=true


[MITM]
hostname = %APPEND% *.cyapi.cn, beta-luna.douyin.com, webcast-open.douyin.com, api.qishui.com
